### PR TITLE
bump underscore to 1.8.3 and backbone to 1.2.1 in bower.json

### PR DESCRIPTION
**Pull request by t1st3**
In my "backbone + marionette + localforage" setup, which uses bower, on install, Bower gets some version mismatch for Underscore:

Unable to find a suitable version for underscore, please choose one:
    1) underscore#~1.6.0 which resolved to 1.6.0 and is required by localforage-backbone#0.6.1
    2) underscore#1.4.4 - 1.8.3 which resolved to 1.8.3 and is required by backbone.radio#0.9.1, marionette#2.4.2
    3) underscore#>=1.4.0 <=1.8.3 which resolved to 1.8.3 and is required by backbone.babysitter#0.1.8
    4) underscore#>=1.3.3 <=1.8.3 which resolved to 1.8.3 and is required by backbone.wreqr#1.3.3
    5) underscore#>=1.5.0 which resolved to 1.8.3 and is required by backbone#1.1.2
    6) underscore#>=1.7.0 which resolved to 1.8.3 and is required by backbone#1.2.1

Every lib in the setup requires Underscore 1.8.3, apart from localForage-backbone, which still wants 1.6.0.  Then, I also bumped Backbone to its latest version 1.2.1

### CODE REVIEW

**Comment by tofumatt** [comment]
I'll clean up the (unrelated) code quality errors here then merge this in. Thanks for the patch!

**Comment by T1st3** [comment]
You're welcome...
I just did the clean up, and everything looks ok now

**Comment by tofumatt** [comment]
Hah, you rock. Thanks! :+1:

**Comment by tofumatt** [comment]
I pushed a new version to npm/bower as well. Thanks again!
- tofumatt

**Pull request merged**
